"""Recompute selected tables and check named quantities and numeric tokens.

Uses bundled records and the standard library only. Named README quantities
check each location and unit; other registrations check numeric tokens within
a document. Unregistered prose is outside these checks.
Without --write this checks the generated tables without changing them.
"""

import argparse
import importlib.util
import json
import math
import re
import statistics
import sys
from pathlib import Path

from doc_claims import check_local_quotes, contains_number

ROOT = Path(__file__).resolve().parents[1]
MEASUREMENTS = ROOT / 'docs/MEASUREMENTS.md'
SAMPLES_PER_PROCESS = 30
PROCESSES_PER_ARM = 3


def load(name):
    return json.loads((ROOT / name).read_text())


def stats(bundle):
    """Recompute p50 and throughput per process, checking the stored summaries."""
    result = {}
    for run in bundle['runs']:
        if run['benchmark_status'] != 'measured':
            continue
        durations = [r['duration_ns'] / 1e6 for r in run['measured_records']]
        assert len(durations) == SAMPLES_PER_PROCESS
        assert len({r['index'] for r in run['measured_records']}) == SAMPLES_PER_PROCESS
        p50 = statistics.median(durations)
        assert math.isclose(p50, run['p50_ms'], abs_tol=1e-12)
        assert run['admission']['benchmark_admitted'] and run['numerical']['passed']
        tops = run['source_ops'] / p50 / 1e9
        assert math.isclose(tops, run['source_equivalent_Tops'], abs_tol=1e-9)
        process = int(re.search(r'process(\d+)', run['run'])[1])
        result.setdefault(run['case_id'], []).append(
            {'process': process, 'p50': p50, 'tops': tops})
    return result


def span(values, digits, suffix=''):
    """Render a min-max range, collapsing it when rounding merges the ends."""
    low, high = f'{min(values):.{digits}f}', f'{max(values):.{digits}f}'
    return (low if low == high else f'{low}–{high}') + suffix


def paired(arms, case, baseline):
    """FP16 over quantized p50, matched within each process round."""
    reference = {r['process']: r['p50'] for r in arms[baseline]}
    return [reference[r['process']] / r['p50'] for r in arms[case]]


def split_ratios(split):
    """Split over wide p50, matched within each process round."""
    wide = {r['process']: r['p50'] for r in split['coreai-a8w4-2']}
    return [r['p50'] / wide[r['process']] for r in split['coreai-a8w4-split32-2']]


def historical():
    records = {r['label']: r for r in load('results/historical/selected-evidence.json')}

    def median(label):
        return statistics.median(r['duration_ns'] / 1e6 for r in records[label]['record_rows'])

    return {
        'tops': records['coreai_w8a8_128']['source_ops'] / median('coreai_w8a8_128') / 1e9,
        'speedup': median('coreai_fp16_128') / median('coreai_w8a8_128'),
        'slowdown': median('split_a8w4_2') / median('wide_a8w4_2'),
    }


def measurements():
    """Build docs/MEASUREMENTS.md from the bundled records."""
    throughput = stats(load('results/fresh/throughput.json'))
    split = stats(load('results/fresh/split.json'))
    smoke = load('results/fresh/smoke.json')

    lines = [
        '# Measurements',
        '',
        'Generated by `python scripts/summarize.py --write` from the bundled per-call '
        'records; `python scripts/summarize.py` checks this file against them. A MAC '
        'counts as two source-graph operations. Scope and limits are in [SCOPE.md](SCOPE.md).',
        '',
        '## 128-layer positive controls',
        '',
        '![Five configurations with three independent-process throughput points each.]'
        '(figures/throughput-by-process.svg)',
        '',
        'Bars show the median process rate; the table gives the full range across the '
        'three processes and the paired ratio against the same round of FP16. '
        '[Figure sources and regeneration](FIGURES.md).',
        '',
        '| Case | Processes | p50 (ms) | Source-equivalent throughput (T ops/s) | vs FP16 |',
        '|---|---:|---:|---:|---:|',
    ]
    for case, rows in throughput.items():
        assert len(rows) == PROCESSES_PER_ARM
        assert {r['process'] for r in rows} == {1, 2, 3}
        baseline = case.split('-')[0] + '-fp16-128'
        ratio = ('—' if case == baseline
                 else span(paired(throughput, case, baseline), 2, '×'))
        lines.append(f'| {case} | {len(rows)} | {span([r["p50"] for r in rows], 3)} '
                     f'| {span([r["tops"] for r in rows], 2)} | {ratio} |')

    lines += [
        '',
        '## Same-weight SplitConv ablation',
        '',
        '![Three paired wide and split latency comparisons, each measured in independent '
        'processes.](figures/split-latency.svg)',
        '',
        'Lines join paired configurations, not a time series. The latency axis starts at zero.',
        '',
        '| Case | Processes | p50 (ms) |',
        '|---|---:|---:|',
    ]
    for case, rows in split.items():
        assert len(rows) == PROCESSES_PER_ARM
        lines.append(f'| {case} | {len(rows)} | {span([r["p50"] for r in rows], 3)} |')
    ratios = split_ratios(split)
    lines += [
        '',
        f'Paired split / wide latency ratios: {span(ratios, 2, "×")} '
        f'({", ".join(f"{v:.2f}×" for v in ratios)} by round).',
        '',
        'Splitting changes the convolution partition and the FP16 reduction and rounding '
        'boundaries together. These measurements do not isolate slicing, narrow-K kernels, '
        'scheduling, fusion or addition as the sole cause.',
        '',
        '## Isolated-wheel smoke observations',
        '',
        '| Case | Numeric controls | ANE participation in all controls | Conv preferred devices |',
        '|---|---|---|---|',
    ]
    assert len(smoke['runs']) == 14
    for run in smoke['runs']:
        plan = run['placement']
        devices = (','.join(sorted({x['preferred'].strip('<>') for x in plan['conv_plan']}))
                   or 'Core AI: per-op mapping unavailable')
        lines.append(f"| {run['case_id']} | {run['numerical']['passed']} "
                     f"| {plan['every_control_has_ANE']} | {devices} |")

    by_case = {r['case_id']: r for r in smoke['runs']}
    lines += ['', 'Rows are observations on the pinned stack; a runtime that fixes a failure '
                  'would change its row.']
    native = by_case['coreai-group-native64']
    if (not native['numerical']['passed']
            and native.get('flattened-scale-hypothesis', {}).get('passed')):
        lines += ['', 'The native Core AI K64 output fails the intended reference and exactly '
                      'matches the separately predicted flattened-scale error.']
    coreml_split = by_case['coreml-group-split32']
    if (not coreml_split['placement']['every_control_has_ANE']
            and all('MLCPUComputeDevice' in x['preferred']
                    for x in coreml_split['placement']['conv_plan'])):
        lines += ['', 'This 64-output Core ML split selected CPU. The historical 15360-output '
                      'Gemma-derived split selected ANE; the shapes are distinct.']

    old = historical()
    lines += ['', f'Historical records stay in `results/historical/`: Core AI W8A8 '
                  f'{old["tops"]:.2f} T ops/s, a paired FP16/W8A8 ratio of '
                  f'{old["speedup"]:.2f}×, and one wide/split process pair at '
                  f'{old["slowdown"]:.2f}×. Those are distinct runs with fewer independent '
                  f'processes.', '']
    return '\n'.join(lines)


def smoke_case(case):
    return next(r for r in load('results/fresh/smoke.json')['runs'] if r['case_id'] == case)


def claims():
    """Numbers the prose must quote, derived here so a document cannot drift.

    Each entry is recomputed from the bundled records; if a value moves, the
    document that quotes it fails this check instead of going stale in silence.
    """
    throughput = stats(load('results/fresh/throughput.json'))
    split = stats(load('results/fresh/split.json'))
    old = historical()
    model = load('results/historical/cross-model-validation.json')
    leaf = load('results/historical/dot-localization.json')['leaf']
    prefill = load('results/historical/ane-vs-gpu-prefill.json')

    def rate(case):
        return span([r['tops'] for r in throughput[case]], 2)

    def ratio(case):
        return span(paired(throughput, case, case.split('-')[0] + '-fp16-128'), 2, '×')

    validated = sum(b['real_values'] for b in model['models'].values())
    residuals = sum(b['q8_numeric_mismatches'] for b in model['models'].values())
    native = smoke_case('coreai-group-native64')['numerical']['comparisons'][0]

    ratios = prefill['ANE_over_GPU_ratios']
    leak = sorted(set(prefill['iosurface_growth_bytes_per_call'].values()))
    assert len(leak) == 1, 'the diagnostic variants no longer agree'
    gpu_gap = [f'{ratios[p]["p50_outer_ms"]:.2f}' for p in ('4096', '1024')]
    activation_speed = (prefill['engines']['C']['rows']['4096']['p50_outer_ms']
                        / prefill['engines']['A']['rows']['4096']['p50_outer_ms'])

    headline = [
        *gpu_gap,                                      # ANE against the GPU, 4K then 1K
        f'{int(leak[0]):,}',                           # bytes leaked per call
        span(split_ratios(split), 2, '×'),             # split / wide latency ratio
        f'{validated:,}',                              # outputs the model reproduces
        str(residuals),                                # residuals it cannot explain
        ratio('coreai-w8a8-128'),                      # paired speed-up over FP16
        str(native['numeric_mismatches']),             # the predictable wrong answer
    ]
    detail = [
        f'{native["relative_L2"]:.6f}',
        repr(leaf['ane_actual']),
        repr(leaf['model_prediction']),
        f'{old["slowdown"]:.2f}×',
        rate('coreai-w8a8-128'),
    ]
    registered = {'README.md': headline + [detail[3]], 'README.zh-CN.md': headline,
            'findings/README.md': [f'{validated:,}', *gpu_gap,
                                   str(native['numeric_mismatches']), f'{int(leak[0]):,}'],
            'findings/ane-vs-gpu-prefill/README.md': gpu_gap,
            'findings/iosurface-per-call-growth/README.md': [f'{int(leak[0]):,}'],
            'findings/execution-model/README.md': [f'{validated:,}', str(residuals)],
            'findings/fp16-dot-residual/README.md': detail[1:3],
            'findings/coreai-flattened-scale/README.md': [detail[0],
                                                          str(native['numeric_mismatches'])],
            'findings/coreai-flattened-scale/repro/README.md': [detail[0],
                str(native['numeric_mismatches']),
                str(math.prod(smoke_case('coreai-group-native64')['output_shape']))],
            'findings/split-decomposition-cost/README.md': [span(split_ratios(split), 2, '×')],
            'workarounds/README.md': [span(split_ratios(split), 2, '×'),
                                      ratio('coreai-w8a8-128'), f'{int(leak[0]):,}']}

    for name in ('README.md', 'README.zh-CN.md', 'findings/README.md',
                 'findings/ane-vs-gpu-prefill/README.md'):
        registered[name].append(f'{activation_speed:.3f}×')

    # Both languages quote the same records. Reuse the numeric-token checks;
    # examples explaining arithmetic are distinct from measured result values.
    raw_throughput = load('results/fresh/throughput.json')['runs']
    w8 = next(r for r in raw_throughput if r['case_id'] == 'coreai-w8a8-128')
    fp16 = throughput['coreai-fp16-128']
    a8w4 = throughput['coreai-a8w4-128']
    first = [ratio('coreai-w8a8-128').removesuffix('×'), f'{w8["source_ops"]:,}',
             f'{w8["source_ops"]/1e12:.4f}',
             f'{load("results/fresh/split.json")["runs"][0]["source_ops"]:,}',
             f'{w8["p50_ms"]:.2f}', f'{w8["source_equivalent_Tops"]:.2f}',
             f'{max(r["tops"] for r in a8w4):.2f}',
             f'{max(r["tops"] for r in a8w4):.0f}',
             f'{statistics.median(r["tops"] for r in fp16):.1f}']
    for values in throughput.values():
        first.extend([span([r['p50'] for r in values], 3),
                      span([r['tops'] for r in values], 2)])
    second = [rate('coreai-w8a8-128'), rate('coreai-a8w4-128'),
              ratio('coreai-w8a8-128'), span(split_ratios(split), 2, '×'),
              *[f'{v:.2f}×' for v in split_ratios(split)],
              *[span([r['p50'] for r in values], 3) for values in split.values()],
              *[span([r['p50'] for r in values], 2) for values in split.values()],
              f'{old["slowdown"]:.2f}×', f'{native["relative_L2"]:.6f}']
    arithmetic = load('results/historical/arithmetic-reference-evidence.json')
    diagnostic = next(s for s in arithmetic['sources']
                      if s['source_relative'].endswith('rounding-diagnostic/result.json'))
    fields = {f['json_pointer']: f['value'] for f in diagnostic['fields']}
    third = [f'{fields["/results/0/relative_L2"]:.6f}',
             f'{fields["/results/1/relative_L2"]:.9f}',
             f'{arithmetic["denominator_recheck"]["relative_L2"]:.2f}',
             f'{w8["numerical"]["comparisons"][0]["relative_L2"]:.6f}',
             f'{w8["RNE-not-gate"]["comparisons"][0]["relative_L2"]:.3f}',
             str(native['numeric_mismatches']), f'{native["relative_L2"]:.6f}',
             str(math.prod(smoke_case('coreai-group-native64')['output_shape']))]
    for case in ('equal', 'unequal', 'reverse_order', 'explicit_q'):
        control = smoke_case('coreai-qdq-' + case)['numerical']['comparisons'][0]
        third.extend([format(control['relative_L2'], '.1f' if case == 'reverse_order' else 'g'),
                      format(control['max_abs'], 'g')])
    for stem, zh_name, values in [
            ('01-measuring-ane-performance', '01-如何验证ANE的量化加速', first),
            ('02-group-quantization-and-split', '02-分组量化如何改变ANE的执行图', second),
            ('03-arithmetic-compatibility', '03-ANE算术兼容性', third),
            ('README', 'README', [f'{max(r["tops"] for r in a8w4):.0f}'])]:
        for name in (f'articles/{stem}.md', f'articles/zh/{zh_name}.md'):
            registered[name] = list(dict.fromkeys(values))
    spec = importlib.util.spec_from_file_location('short_query_verify', ROOT / 'findings/ane-short-decode-query/repro/verify.py')
    short_query = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(short_query)
    _, rows = short_query.outcomes()
    registered['findings/ane-short-decode-query/README.md'] = sorted(
        {str(r['ane_requests_before_failure']) for r in rows if r['ane_requests_before_failure']})
    spec = importlib.util.spec_from_file_location('palettized_verify', ROOT / 'findings/coreai-palettized-weights-gpu/repro/verify.py')
    palettized = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(palettized)
    rows = palettized.placement()
    registered['findings/coreai-palettized-weights-gpu/README.md'] = [
        str(rows['fp16']['ane_requests']), str(rows['w4']['metal_shader_compiles'])]
    environment = load('results/historical/g2-w4a16-night/environment.json')
    for name in ('articles/04-w4a16-service-tradeoffs.md',
                 'articles/zh/04-W4A16留在ANE上值得吗.md'):
        registered[name] = [
            str(environment['background_snapshots'])]
    return registered


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true',
                        help='Regenerate docs/MEASUREMENTS.md instead of checking it')
    args = parser.parse_args()
    from g2.evidence import derive, measurements as g2_measurements, quoted_values
    g2 = derive()
    from g3.evidence import derive as derive_g3, measurements as g3_measurements
    g3 = derive_g3()
    from g1w.evidence import derive as derive_g1w, measurements as g1w_measurements, quoted_values as g1w_quotes
    from g5.evidence import derive as derive_g5, measurements as g5_measurements, quoted_values as g5_quotes
    g1w, g5 = derive_g1w(), derive_g5()
    from g4a.evidence import derive as derive_g4a, measurements as g4a_measurements
    g4a = derive_g4a()
    from g6.evidence import derive as derive_g6, measurements as g6_measurements
    g6 = derive_g6()
    from g7.evidence import derive as derive_g7, measurements as g7_measurements
    g7 = derive_g7()
    text = (measurements() + '\n' + g2_measurements(g2) + '\n' + g3_measurements(g3) + '\n'
            + g1w_measurements(g1w) + '\n' + g5_measurements(g5) + '\n' + g4a_measurements(g4a) + '\n' + g6_measurements(g6)
            + '\n' + g7_measurements(g7))
    if args.write:
        MEASUREMENTS.write_text(text)
        print(f'wrote {MEASUREMENTS.relative_to(ROOT)}')
        return

    from g3.claims import check as check_g3_quotes
    from g4a.claims import check as check_g4a_quotes
    from component_claims import check as check_component_quotes
    from g1w.claims import quantities as g1w_quantities
    from g5.claims import quantities as g5_quantities
    from g6.claims import quantities as g6_quantities
    from g7.claims import quantities as g7_quantities
    problems = (check_local_quotes(ROOT, g2) + check_g3_quotes(ROOT, g3) + check_g4a_quotes(ROOT, g4a)
                + check_component_quotes(ROOT, 'g1w', g1w_quantities(g1w))
                + check_component_quotes(ROOT, 'g5', g5_quantities(g5))
                + check_component_quotes(ROOT, 'g6', g6_quantities(g6))
                + check_component_quotes(ROOT, 'g7', g7_quantities(g7)))
    if MEASUREMENTS.read_text() != text:
        problems.append('docs/MEASUREMENTS.md differs from the bundled records; '
                        'rerun with --write')
    registered = claims()
    for quotes in (quoted_values(g2), g1w_quotes(g1w), g5_quotes(g5)):
        for name, values in quotes.items():
            registered.setdefault(name, []).extend(values)
    for name, required in registered.items():
        body = (ROOT / name).read_text()
        for value in required:
            if not contains_number(body, value):
                problems.append(f'{name} does not quote the recomputed value {value!r}')
    if problems:
        for problem in problems:
            print('FAIL:', problem, file=sys.stderr)
        raise SystemExit(1)
    checked = sum(len(v) for v in registered.values())
    print(f'measurement tables and named README references verified; {checked} registered values match the records')


if __name__ == '__main__':
    main()
